### ISSUE TITLE
escort 0.4.0 breaks simplecov, possible to release new gem?

### ISSUE THREAD

**Issue by GeoffWilliams** [skorks/escort#13]
Hi,

I really like Escort!  Is it still being developed?  If require the escort 0.4.0 gem in a project that is using simplecov for code coverage, I get a error but this has already been fixed in master.  Are there any plans to release an updated gem?

## Analysis
The error is encountered after all rspec tests have been run when simplecov is writing its report.  Since this is an unhandled error it causes ruby to exit with failed status and marks good builds as bad:

```shell
/Users/geoff/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/lib/simplecov-html.rb:25:in `write': closed stream (IOError)
	from /Users/geoff/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/lib/simplecov-html.rb:25:in `puts'
	from /Users/geoff/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/lib/simplecov-html.rb:25:in `puts'
	from /Users/geoff/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/lib/simplecov-html.rb:25:in `format'
	from /Users/geoff/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/simplecov-0.12.0/lib/simplecov/result.rb:47:in `format!'
	from /Users/geoff/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/simplecov-0.12.0/lib/simplecov/configuration.rb:172:in `block in at_exit'
	from /Users/geoff/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/simplecov-0.12.0/lib/simplecov/defaults.rb:67:in `call'
	from /Users/geoff/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/simplecov-0.12.0/lib/simplecov/defaults.rb:67:in `block in <top (required)>'
/Users/geoff/.rbenv/versions/2.2.6/bin/ruby -I/Users/geoff/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/lib:/Users/geoff/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/rspec-support-3.5.0/lib /Users/geoff/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

This is already fixed in master in commit 0ade8fb6f02b58f3c7f73962375c0cb2a5f744f0 :

```diff
-at_exit do
-  Escort::Logger.close
-end
```

**Comment by enchf** [comment]
Hi,

You can use this trick:
In your Gemfile include escort in this way:

`gem 'escort',           git: 'git://github.com/skorks/escort.git'`

It will download the gem directly from github, branch master.
